# Generated by Django 5.0.3 on 2024-12-11 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refriges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='기본 식품 이름')),
                ('image', models.ImageField(upload_to='food_images/', verbose_name='기본 식품 이미지')),
            ],
            options={
                'verbose_name': '기본 식품',
                'db_table': 'default_food',
            },
        ),
        migrations.CreateModel(
            name='FridgeFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='사용자 정의 식품 이름')),
                ('purchase_date', models.DateField(verbose_name='구매 날짜')),
                ('expiration_date', models.DateField(verbose_name='소비기한')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('default_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_foods', to='foods.defaultfood', verbose_name='기본 식품')),
                ('refrigerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refrigerator_foods', to='refriges.refrigerator', verbose_name='냉장고')),
            ],
            options={
                'verbose_name': '냉장고 식품',
                'verbose_name_plural': '냉장고 식품',
                'db_table': 'fridge_food',
            },
        ),
        migrations.CreateModel(
            name='FoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('consumed', 'Consumed'), ('discarded', 'Discarded')], max_length=10, verbose_name='행동 유형')),
                ('quantity', models.PositiveIntegerField(help_text='소비하거나 폐기한 수량', verbose_name='수량')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='기록 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_histories', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('fridge_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_histories', to='foods.fridgefood', verbose_name='냉장고 식품')),
            ],
            options={
                'verbose_name': '식품 기록',
                'verbose_name_plural': '식품 기록',
                'db_table': 'food_history',
            },
        ),
    ]
