# Generated by Django 5.0.3 on 2024-12-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultfood',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='기본 식품 알림멘트'),
        ),
        migrations.AddField(
            model_name='foodhistory',
            name='food_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='음식 이름'),
        ),
        migrations.AlterField(
            model_name='foodhistory',
            name='fridge_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_histories', to='foods.fridgefood', verbose_name='냉장고 식품 ID'),
        ),
    ]
