# Generated by Django 5.0.3 on 2025-01-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_defaultfood_comment_foodhistory_food_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgefood',
            name='storage_type',
            field=models.CharField(choices=[('refrigerated', '냉장'), ('frozen', '냉동'), ('room_temp', '실온')], default='refrigerated', max_length=20, verbose_name='보관 방식'),
        ),
    ]
