# Generated by Django 5.0.3 on 2025-01-14 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_fridgefood_storage_type'),
        ('refriges', '0005_alter_refrigeratorinvitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodhistory',
            name='refrigerator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_histories', to='refriges.refrigerator', verbose_name='냉장고'),
        ),
    ]
