# Generated by Django 5.0.3 on 2025-01-30 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_foodhistory_refrigerator'),
        ('refriges', '0004_alter_refrigeratorinvitation_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodhistory',
            index=models.Index(fields=['refrigerator'], name='idx_refrigerator'),
        ),
        migrations.AddIndex(
            model_name='foodhistory',
            index=models.Index(fields=['user'], name='idx_user'),
        ),
        migrations.AddIndex(
            model_name='foodhistory',
            index=models.Index(fields=['action'], name='idx_action'),
        ),
        migrations.AddIndex(
            model_name='foodhistory',
            index=models.Index(fields=['timestamp'], name='idx_timestamp'),
        ),
        migrations.AddIndex(
            model_name='foodhistory',
            index=models.Index(fields=['refrigerator', 'action', 'timestamp'], name='idx_refrige_action_timestamp'),
        ),
        migrations.AddIndex(
            model_name='foodhistory',
            index=models.Index(fields=['user', 'action', 'timestamp'], name='idx_user_action_timestamp'),
        ),
    ]
