# Generated by Django 5.0.3 on 2024-12-11 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이미지 이름')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='프로필 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='이미지 생성 시간')),
            ],
            options={
                'verbose_name': '프로필 이미지',
                'db_table': 'profile_image',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='닉네임')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('kakao_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='카카오 고유 ID')),
                ('is_social', models.BooleanField(default=False, verbose_name='소셜 로그인 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 사용자 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 권한')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='슈퍼유저 권한')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='정보 수정 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입 날짜')),
                ('image', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profileimage', verbose_name='프로필 이미지')),
            ],
            options={
                'verbose_name': '사용자',
                'db_table': 'user',
            },
        ),
    ]
