# Generated by Django 5.0.3 on 2024-12-11 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='냉장고 이름')),
                ('description', models.TextField(blank=True, null=True, verbose_name='냉장고 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
            ],
            options={
                'verbose_name': '냉장고',
                'db_table': 'refrigerator',
            },
        ),
        migrations.CreateModel(
            name='RefrigeratorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], max_length=10, verbose_name='사용자의 역할')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='권한 부여 날짜')),
                ('refrigerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='refriges.refrigerator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refrigerator_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '냉장고 공유',
                'db_table': 'refrigerator_access',
            },
        ),
        migrations.AddConstraint(
            model_name='refrigeratoraccess',
            constraint=models.UniqueConstraint(fields=('user', 'refrigerator'), name='unique_user_refrigerator'),
        ),
    ]
