# Generated by Django 5.0.3 on 2024-12-28 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refriges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefrigeratorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254, verbose_name='초대받은 사람 이메일')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10, verbose_name='초대 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='초대 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='상태 변경 날짜')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='초대한 사람')),
                ('refrigerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='refriges.refrigerator', verbose_name='냉장고')),
            ],
            options={
                'verbose_name': '냉장고 초대',
                'verbose_name_plural': '냉장고 초대',
                'db_table': 'refrigerator_invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefrigeratorMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='메모 제목')),
                ('content', models.TextField(verbose_name='메모 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('refrigerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='refriges.refrigerator', verbose_name='냉장고')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '냉장고 메모',
                'verbose_name_plural': '냉장고 메모',
                'db_table': 'refrigerator_memo',
                'ordering': ['-created_at'],
            },
        ),
    ]
