# Generated by Django 5.0.3 on 2025-01-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refriges', '0002_refrigeratorinvitation_refrigeratormemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigeratorinvitation',
            name='code',
            field=models.CharField(default='RiBIRah7_gCpH8QHiwKZhA', max_length=50, unique=True, verbose_name='초대 코드'),
        ),
    ]
